### ISSUE TITLE
How to call this plugin from JavaScript ?

### ISSUE THREAD

**Issue by vishvendu** [duddu/cordova-plugin-antitampering#1]

**Comment by duddu** [comment]
The plugin exports an AntiTampering class, exposing a method to trigger the native operations.

From JavaScript call:
`window.cordova.plugins.AntiTampering.verify(<Function>successCallback, <Function>errorCallback)`;

Instead, if you got AngularJS in your project, you can simply import the `duddu.antitampering` module and inject the `$antitampering` angular service; the `verify` method returns a promise:
`$antitampering.verify().then(<Function>successCallback, <Function>errorCallback);`

I will fill the README with all the instructions as soon as I can. Meanwhile, tell me if you have any question.

**Comment by WuglyakBolgoink** [comment]
Hallo @duddu,

any updates in README-Help will be nice!

Next question:
- **Response**: `SUCCESS $antitampering:{"assets":{"count":64}}`

```json
{
    "assets": {
        "count": 64
    }
}
```

so.. 
- what I need to know in this case? 
- `64` - is a count of my `valid` files or all files in `assets` folder?
- if file/files was changed -> what I have at the end : success or error callback?
  - if `success` ->  count will be lower?

**Comment by duddu** [comment]
The "count" property tells the total number of assets checked by the plugin. If a tampering was detected, the verify method would give you an error callback (with the path of the changed file).
That property in the success callback is just a debug information, to double-check the work of the plugin; it will always be the same until the number of the assets change.

I'm finishing the readme right now, sorry for being so slow!

**Comment by duddu** [comment]
Readme updated with version 0.1.0
