### ISSUE TITLE
Unable to install in cordova version 9.0.0

### ISSUE THREAD

**Issue by GhooglePlay** [duddu/cordova-plugin-antitampering#20]
![image](https://user-images.githubusercontent.com/32056382/59658451-47278a00-91c1-11e9-971f-c8df8c3411d7.png)

This plugin doesn't works with cordova 9.0.0 version, anybody had a solution for that? Please find the attached screenshot.

**Comment by yadujaryal** [comment]
have u found any solution , same issue.

**Comment by GhooglePlay** [comment]
> have u found any solution , same issue.

No I haven't, only option left is download cordova version

**Comment by duddu** [comment]
Hi @GhooglePlay @yadujaryal 
Sorry to keep you waiting. Just published to npm the latest release 0.4.0 with fixed support to Cordova 9 (#23).
Please let me know if you still have issues.
