### ISSUE TITLE
Hash cleansing is extremely slow

### ISSUE THREAD

**Issue by jsanta** [duddu/cordova-plugin-antitampering#8]
When there are a lot of hashes, the regexp matching becomes quite slow.
It's far faster to overwrite that file with the original and clean file (that has no  hashes on it).

After a few failed compilations on a dirty base code (with all libs and dependencies brought by bower), my hash file registered more than 100 files. My official compilation task removes most of them, leaving no more than 15.

Best regards.

**Comment by duddu** [comment]
Sorry it was a malformed regex, I fixed in develop and will release in a few hours in master with a new release tag.

**Comment by duddu** [comment]
Should be solved with 0.1.2, please let me know if it still occurs
